version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 2000000000token
  - 200000000stake
  - 200000000upetri
  mnemonic: wine rich chunk that swim afford found auction travel dentist razor furnace
    fluid hidden happy enroll pilot dragon market broom bus merry salad assume
- name: bob
  coins:
  - 10000token
  - 100000000stake
  - 200000000upetri
  mnemonic: major spatial spoil earn capable receive tourist bronze call coral mango
    betray demand size certain strike decline pluck baby eight maple pyramid cage
    cabbage
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
  - 200000000upetri
  host: 0.0.0.0:4500
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    petrichor:
      assets:
      - denom: upetri
        reward_weight: "0.5"
        take_rate: "0.000005"
      - denom: bpetri
        reward_weight: "0.9"
        take_rate: "0.0000009"
      - denom: token
        reward_weight: "5"
        take_rate: "0.0000009"
      params:
        take_rate_claim_interval: 10s
        reward_delay_time: 60s
validators:
- name: alice
  bonded: 100000000stake
  home: ./.testnet
